services:
  baota:
    image: wwkiyyx/baota:ubuntu1
    ports:
      - 8888:8888
      - 80:80
  ttyd1:
    image: wwkiyyx/tthd:tsl0922
    ports:
      - 7682:7681
  ttyd2:
    image: wwkiyyx/tthd:cloudve
    ports:
      - 7683:7681