services:
  code:
    image: wwkiyyx/vscode:yolo
    ports:
      - 8080:8080
    volumes:
      - files:/home/coder
  ubuntulxde:
    image: dorowu/ubuntu-desktop-lxde-vnc
    ports:
      - 8080:80
      - 5900:5900
  ubuntuxfce:
    image: consol/ubuntu-xfce-vnc
    ports:
      - 8901:5901
      - 9901:6901
  centosxfce:
    image: consol/centos-xfce-vnc
    ports:
      - 8901:5901
      - 9901:6901

volumes:
  files:
    driver_opts:
      size: 5Gi